version: '3'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sales_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network  # Ensure this line is here

  backend:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"  # Make sure this line is here to expose port 8000
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://admin:password@db:5432/sales_db"
    networks:
    - app-network

# Define the custom network here
networks:
  app-network:   # Ensure this block exists

volumes:
  postgres-data: